In [29]:
# =============================================================================
# Assignment: 9
# Filename: question1.py
# Description: Numpy assignments
# Date: 03/08/2020
# Author: Tarini Dash
# =============================================================================

import numpy as np

# The main function
def main():
    scores_all = genfromtxt("Scores_all.csv", delimiter = ",")
    scores = scores_all[1:]
    scores[np.isnan(scores)] = 0
    scores = scores.astype(int)
    np.save("scores",scores)
    print(scores)
    
# invoke main function    
main()

[[    0   100   100 ...    10    10   100]
 [49647    90   100 ...     2     6    89]
 [49865   100    70 ...     1     7    73]
 ...
 [29288   100    90 ...    10    10    74]
 [34759   100    90 ...     8     9    94]
 [45920    85    85 ...     0    10    91]]
